
name = "mexico-logistics-query"
compatibility_date = "2025-09-03"

[build]
command = "npx wrangler deploy"

# Define the site bucket (the folder containing your static files)
[site]
bucket = "./"  # Specifies the current directory containing index.html, logo.png, etc.
entry-point = "./worker.js"  # Specifies the worker entry point
