name = "mexico-logistics-query"
compatibility_date = "2025-09-03"

[build]
command = "npx wrangler deploy"

[[site]]
bucket = "./"  # 指定当前目录作为静态文件的目录
entry-point = "./worker.js"  # 指定 worker.js 作为入口文件
