name = "mexico-logistics-query"
compatibility_date = "2025-09-03"

[build]
command = "npx wrangler deploy"

[[site]]
bucket = "./"  # 指向包含静态文件的目录（index.html、logo.png等）
entry-point = "./worker.js"  # Worker 代码的入口文件
